# config.yaml

#
# Base Url is the prefix (ex: https://server:port) for all the API requests
# contained in the excel file.  This is useful when you have to run the same
# set of API requests on different environments (dev, staging, production)
base_url: http://localhost:3000
#base_url: https://cpaas.comviva.com/api
#base_url: http://172.25.47.153:32606/api

start_row: 1 # start row from where to start processing
#end_row: 100  # enale this to limit the number of rows to be processed
verbose: false # wheter to print request and response debug info

token_key: "token" # key name for token in response
